WITH RANKEDEMPLOYEE AS (
    SELECT 
        *,
        DENSE_RANK() OVER(
            PARTITION BY DEPARTMENTID
            ORDER BY SALARY DESC
        ) AS RNK
    FROM EMPLOYEE
)

SELECT
    D.NAME AS DEPARTMENT,
    R.NAME AS EMPLOYEE,
    R.SALARY
FROM RANKEDEMPLOYEE R
JOIN DEPARTMENT D
ON R.DEPARTMENTID = D.ID
WHERE RNK <= 3;