SELECT 
    U.USER_ID AS BUYER_ID,
    U.JOIN_DATE,
    COUNT(CASE 
            WHEN EXTRACT(YEAR FROM O.ORDER_DATE) = 2019 THEN 1 
         END) AS ORDERS_IN_2019
FROM USERS U
LEFT JOIN ORDERS O 
ON U.USER_ID = O.BUYER_ID
GROUP BY U.USER_ID;
 
