WITH FIRST_ORDER AS (
    SELECT 
        CUSTOMER_ID,
        ORDER_DATE,
        CUSTOMER_PREF_DELIVERY_DATE,
        CASE
            WHEN ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE THEN 'IMMEDIATE'
            ELSE 'SCHEDULED'
        END AS TYPE,
        ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE) AS RN
    FROM DELIVERY
)

SELECT 
    ROUND(
        100.0 * SUM(CASE WHEN TYPE = 'IMMEDIATE' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS IMMEDIATE_PERCENTAGE
FROM FIRST_ORDER
WHERE RN = 1;

-- OTHER SOLUTUION

-- WITH FIRST_ORDER AS (
--     SELECT 
--         CUSTOMER_ID,
--         MIN(ORDER_DATE) AS FIRST_ORDER_DATE
--     FROM DELIVERY
--     GROUP BY CUSTOMER_ID
-- )

-- SELECT 
--     ROUND(
--         100.0 * SUM(
--             CASE 
--                 WHEN D.ORDER_DATE = D.CUSTOMER_PREF_DELIVERY_DATE THEN 1 
--                 ELSE 0 
--             END
--         ) / COUNT(*),
--         2
--     ) AS IMMEDIATE_PERCENTAGE
-- FROM DELIVERY D
-- JOIN FIRST_ORDER F
-- ON D.CUSTOMER_ID = F.CUSTOMER_ID 
-- AND D.ORDER_DATE = F.FIRST_ORDER_DATE;