WITH WGT AS (
    SELECT 
        PERSON_NAME,  
        TURN,
        SUM(WEIGHT) OVER (ORDER BY TURN) AS RUNNING_SUM
    FROM QUEUE
)

SELECT PERSON_NAME
FROM WGT
WHERE RUNNING_SUM <= 1000
ORDER BY TURN DESC
LIMIT 1;
