WITH DAILYTOTALS AS (
    SELECT 
        VISITED_ON, 
        SUM(AMOUNT) AS DAY_SUM
    FROM CUSTOMER
    GROUP BY VISITED_ON
),
CALC AS (
    SELECT 
        VISITED_ON,
        SUM(DAY_SUM) OVER(
            ORDER BY VISITED_ON 
            ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
        ) AS AMOUNT,
        ROUND(AVG(DAY_SUM) OVER(
            ORDER BY VISITED_ON 
            ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
        ), 2) AS AVERAGE_AMOUNT,
        ROW_NUMBER() OVER(ORDER BY VISITED_ON) AS RN
    FROM DAILYTOTALS
)
SELECT 
    VISITED_ON,
    AMOUNT,
    AVERAGE_AMOUNT
FROM CALC
WHERE RN >= 7
ORDER BY VISITED_ON;
