SELECT
    D.NAME AS DEPARTMENT,
    E.NAME AS EMPLOYEE,
    E.SALARY AS SALARY
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON E.DEPARTMENTID = D.ID
WHERE E.SALARY = (
    SELECT MAX(E2.SALARY)
    FROM EMPLOYEE E2
    WHERE E.DEPARTMENTID = E2.DEPARTMENTID
);
 
