SELECT
    ID,
    COUNT(ID) AS NUM
FROM (
    SELECT REQUESTER_ID AS ID FROM REQUESTACCEPTED
    UNION ALL
    SELECT ACCEPTER_ID AS ID FROM REQUESTACCEPTED
) AS ALL_FRIENDS
GROUP BY ID
ORDER BY NUM DESC
LIMIT 1;
 
