SELECT
    ST.STUDENT_ID,
    ST.STUDENT_NAME,
    SU.SUBJECT_NAME,
    COUNT(E.SUBJECT_NAME) AS ATTENDED_EXAMS
FROM STUDENTS ST
CROSS JOIN SUBJECTS SU
LEFT JOIN EXAMINATIONS E
    ON ST.STUDENT_ID = E.STUDENT_ID
    AND SU.SUBJECT_NAME = E.SUBJECT_NAME
GROUP BY ST.STUDENT_ID, ST.STUDENT_NAME, SU.SUBJECT_NAME
ORDER BY ST.STUDENT_ID, SU.SUBJECT_NAME;
 
