SELECT NAME AS CUSTOMERS
FROM CUSTOMERS C
WHERE NOT EXISTS (
    SELECT 1
    FROM ORDERS O
    WHERE C.ID = O.CUSTOMERID
);

-- SELECT C.NAME AS CUSTOMERS
-- FROM CUSTOMERS C
-- LEFT JOIN ORDERS O
-- ON C.ID = O.CUSTOMERID
-- WHERE O.CUSTOMERID IS NULL;